### ISSUE TITLE
Helm chart service doesn't work with pod from StatefulSet

### ISSUE THREAD

**Issue by mikitasolo** [stefanprodan/mgob#114]
Currently helm chart service has selectors by `app` and `role`:
```
selector:
    app: {{ template "fullname" . }}
    role: {{ .Values.selector.role }}
```
But StatefulSet template sets only `role` label:
```
template:
    metadata:
      labels:
        role: {{ .Values.selector.role }}
```
As result created service can't attach to the pod
