### ISSUE TITLE
Clean way to backup a target using SSL?

### ISSUE THREAD

**Issue by floweb** [stefanprodan/mgob#12]
Hello,

To begin with, thank you very much for this awesome work!

The situation here is that I need to backup a mongod that uses SSL encryption (eg. MongoDB Atlas).

I think I've found my way out using the `target: password:` field in my .yml plan file, since I can't find any mention of `--ssl` parameter in your code, but it feels a bit too hacky for me.

Maybe I missed something... and you can enlighten me on that, thank you!

**Comment by stefanprodan** [comment]
Hi, 

There is no support for SSL, when I have some free time I'll implement that

**Comment by floweb** [comment]
Thank you for your quick response.

To be honest, **it does work** atm, but it's a little bit hacky!

Just to be clear, I injected the `--ssl --sslAllowInvalidCertificates` parameters through my .yml plan file.
(I don't know if it was clear enough in my first message.)

Here is an abstract of the .yml plan file I used:
```yaml
target:
  host: "myhost.mongodb.net"
  username: "<myusername>"
  password: "<mypassword> --ssl --sslAllowInvalidCertificates"
```

And it worked !
