### ISSUE TITLE
on demand backup - blank screen

### ISSUE THREAD

**Issue by Daxcor69** [stefanprodan/mgob#140]
When I issue all the commands, mgob works just fine. It shows I have a sched backup.  When I try to do on demand backup

http://ip:8090/backup/founy

with a config file called,   founy.yml

```
scheduler:
  # run every day at 6:00 and 18:00 UTC
  cron: "0 6,18 */1 * *"
  # number of backups to keep locally
  retention: 7
  # backup operation timeout in minutes
  timeout: 60
target:
  # mongod IP or host name
  host: "mongo"
  # mongodb port
  port: 27017
  # mongodb database name, leave blank to backup all databases
  database: "foury"
  # leave blank if auth is not enabled
  username: "admin"
  password: "Vug"
s3:
  url: "https://foury.nyc3.digitaloceanspaces.com"
  bucket: "backups"
  accessKey: "GIA4"
  secretKey: "CKwTGUEJM07x0"
  api: "S3v4"
```

I just get a blank screen in my browser window.  I am launching this in a docker compose file.

```
mongo_backup:
    image: stefanprodan/mgob:latest
    volumes:
      - /mgob/config:/config
      - /mgob/storage:/storage
      - /mgob/tmp:/tmp
      - /mgob/data:/data
    ports:
      - 8090:8090
    deploy:
      placement:
        constraints:
          - node.hostname == www1
      restart_policy:
        condition: on-failure
    hostname: mongo_backup
    networks:
      - website_overlay

```

When I look  in the data dir on the host, I see the mgob.db file present.

Thanks for  having a look.

Brad
