### ISSUE TITLE
Insufficient permissions connecting to Wasabi 

### ISSUE THREAD

**Issue by kyi87** [stefanprodan/mgob#153]
Hi, i want to add Wasabi as S3-Storage. But i get the following error:

```
time="2022-02-01T18:34:06Z" level=error msg="Backup failed S3 uploading /storage/backup/backup-1643740440.gz to backup/<MYBUCKETNAME> failed `/storage/backup/backup-1643740440.gz` 
-> `backup/<MYBUCKETNAME>/backup-1643740440.gz` mc: <ERROR> Failed to copy `/storage/backup/backup-1643740440.gz`. Insufficient permissions to access this file `https://s3.eu-central-1.wasabisys.com/<MYBUCKETNAME>/backup-1643740440.gz` Total: 0 B, Transferred: 480.00 KiB, Speed: 4.00 MiB/s : exit status 1" plan=backup
```

My configuration:
```
...
s3:
  url: "https://s3.eu-central-1.wasabisys.com"
  bucket: "<MYBUCKETNAME>"
  accesskey: "<MYACCESSKEY>"
  secretkey: "<MYSECRETKEY>"
  api: "s3v4"
...
```

Wasabi should be fully supported: "Because Wasabi is 100% bit-compatible with Amazon S3, any tool, gateway, or related product that is S3-compatible should work with Wasabi." (https://wasabi.com/wp-content/uploads/2021/09/Wasabi_API_Guide-2.pdf)

Do you have an idea?

Thanks.
