### ISSUE TITLE
Failed: error connecting to db server: no reachable servers

### ISSUE THREAD

**Issue by lukywong** [stefanprodan/mgob#18]
Hi, error ocurred when i try to backup db, here is my plan
``` yml
scheduler:
  # run every day at 19:00 UTC (Beijing 3:00 AM)
  # cron: "0 19 */1 * *"
  cron: "*/1 * * * *"
  # number of backups to keep locally
  retention: 14
  # backup operation timeout in minutes
  timeout: 60
target:
  # mongod IP or host name
  host: "127.0.0.1"
  # mongodb port
  port: 27017
  # mongodb database name, leave blank to backup all databases
  database: "studyland"
  # leave blank if auth is not enabled
  username: ""
  password: ""
  # username: "admin"
  # password: "secret"
  # # add custom params to mongodump (eg. Auth or SSL support), leave blank if not needed
  # params: "--ssl --authenticationDatabase admin"
```
