### ISSUE TITLE
add minikube configuration and chart

### ISSUE THREAD

**Issue by russt** [stefanprodan/mgob#39]
Would be nice to have a configuration guide to create a fully functioning minikube test configuration for mgob.  Suggest separate directory to document helm chart and storage provisioning required for minikube, or perhaps add commented section for minikube in values.yaml:

Changes to values.yaml for helm chart to provision minikube storage:
```
storage:
  longTerm:
    accessMode: "ReadWriteOnce"
    storageClass: "manual"
    name: "mgob-storage"
    size: 5Gi
  tmp:
    accessMode: "ReadWriteOnce"
    storageClass: "manual"
    name: "mgob-tmp"
    size: 1Gi
```

Config to create storage:
```
kubectl apply -f - << EOF
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/pv0001/
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0002
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/pv0002/
EOF
```
Create storage directories on minikube:
```
minikube ssh sudo mkdir /data/pv0001
minikube ssh sudo mkdir /data/pv0002
```
Install mongodb from helm chart:
```
helm install stable/mongodb
```
All that remains is to add mgob config to backup database "local" and "admin" of default mongodb to provide a fully functional example.
