### ISSUE TITLE
Pass database credentials as secret

### ISSUE THREAD

**Issue by IngaldiCSB** [stefanprodan/mgob#58]
Hello!

in kubernetes manifests, I describe a mgob configuration file, mounted as configMap. In this file i have to provide user database credentials and it's not a good practice. Is there some way to configure db credentials creating a secret and mounting it along mogb configuration?

Thanks in advance and congratulations for the project

**Comment by stefanprodan** [comment]
The mogb config files can be stored as Secrets instead of ConfigMaps.

**Comment by bzon** [comment]
@stefanprodan I think it can be a good user experience to still be able to see my configs and use a secret. How about the following?

```yaml
target:
  host: "172.18.7.21"
  port: 27017
  database: "test"
  username: "admin"
#  password: "secret"
  k8s_secret:
    name: mgob-secret
    key: MONGODB_PASSWORD
```

 I can help with this one if you think it is ok.
