### ISSUE TITLE
gcloud failed: exit status 1

### ISSUE THREAD

**Issue by MostHated** [stefanprodan/mgob#66]
Hello, I am getting the following errors:

```
mgob | time="2019-04-09T03:11:50Z" level=info msg="On demand backup started" plan="mongodb_backup"
mgob | time="2019-04-09T03:11:51Z" level=error msg="On demand backup failed gcloud auth for plan mongodb_backup failed: exit status 1" plan="mongodb_backup"
```

I have storage object admin set on the service account as seen below:

![](https://i.imgur.com/TOBvMXK.png)

I have the path correct in the config and I double checked my file endings to make sure they are LF/UTF-8.  I attempted to test it using - curl -X POST http://localhost:8090/backup/mongodb_backup

I am using docker-compose with the following config:

```yaml

version: '3.7'

services:
  mgob:
    image: stefanprodan/mgob:latest
    container_name: mgob
    restart: always
    volumes:
      - /home/<myUser>/devtools/nodebb/mgob/mgob-config:/config
      - mgob-storage:/storage
      - mgob-data:/data
      - mgob-tmp:/tmp
    # depends_on:
    #   - mongodb
    ports:
      - 8090:8090
    networks:
      - backup

volumes:
  mgob-storage:
    driver: local
    driver_opts:
      o: bind
      device: /mnt/disks/data_mongodb/_backup/storage
  mgob-data:
    driver: local
    driver_opts:
      o: bind
      device: /mnt/disks/data_mongodb/_backup/data
  mgob-tmp:
    driver: local
    driver_opts:
      o: bind
      device: /mnt/disks/data_mongodb/_backup/tmp

networks:
  backup:
    external:
      name: nodebb_net

```

Here is the mgob config:

```yaml

scheduler:
  # run every day at 6:00 and 18:00 UTC
  cron: "0 6,18 */1 * *"
  # number of backups to keep locally
  retention: 5
  # backup operation timeout in minutes
  timeout: 60
target:
  # mongod IP or host name
  host: "mongodb"
  # mongodb port
  port: 27017
  # mongodb database name, leave blank to backup all databases
  database: "nodebb"
  # leave blank if auth is not enabled
  username: "<myuser>"
  password: "<mypass>"
  # add custom params to mongodump (eg. Auth or SSL support), leave blank if not needed
  params: "--authenticationDatabase admin"
# GCloud upload (optional)
gcloud:
  bucket: "<mybucket>-backups"
  keyFilePath: /home/<myUser>/devtools/nodebb/mgob/mgob-credentials/service-account.json


```

Does anyone, perhaps, have any other suggestions?
Thanks,
-MH
