### ISSUE TITLE
s3 directory

### ISSUE THREAD

**Issue by bsormagec** [stefanprodan/mgob#73]
can you add directory support for s3 ? thanks..

**Comment by easybi-at** [comment]
yes please !!! we dont use a bucket per every mongodb... we have one bucket called backup, with different projects inside, inside projects we have environments like staging/production and after that folders like mysql, mongodb, files ... so I cannot use mgob without this option. If you find time, please help :) should be fairly simple, because minio does support them.

**Comment by ivanbeldad** [comment]
You just have to add the path to the `bucket` property.

```
s3:
  url: "https://s3-eu-west-1.amazonaws.com/"
  bucket: "my-bucket/folder/"
  accessKey: ""
  secretKey: ""
  api: "S3v4"
```

Remember to add the final slash (otherwise it'll think it is the filename).
