### ISSUE TITLE
Related to sensitive information in configmap

### ISSUE THREAD

**Issue by polganesh** [stefanprodan/mgob#74]
Hi,
I am trying to configure Mgob for our application which is running in Azure k8s service as a backup agent.
while going through documentation i observed that we can create backup plan 
it has two important things
```
target:
 password: "secret"  
azure:
  containerName: "backup"
  connectionString: 
"DefaultEndpointsProtocol=https;AccountName=...;AccountKey=...;EndpointSuffix=core.windows.net"
```

do we have any way by which we can pull this information from secret instead of exposing it directly in config map
