### ISSUE TITLE
SFTP backup upload ssh: handshake failed

### ISSUE THREAD

**Issue by YRPRO** [stefanprodan/mgob#84]
Hello,

I have an issue regarding the upload of the backup to an SFTP server.

The backup phase proceed without error it's seems to be something with the ssh handshake.
Here the error message in the log : 

`time="2019-08-20T12:07:00Z" level=error msg="Backup failed SSH dial to SFTP-SERVER-IP:21 failed: ssh: handshake failed: ssh: invalid packet length, packet too large" plan=dev-mongo-backup-plan 
`

Here my backup plan : 
```

scheduler:
  # every 15 min for test
  cron: "*/15 * * * *"
  # number of backups to keep locally
  retention: 2
  # backup operation timeout in minutes
  timeout: 60
target:
  # mongod IP or host name
  host: "MONGO-IP"
  # mongodb port
  port: 27018
  # mongodb database name, leave blank to backup all databases
  database: "dev"
  # leave blank if auth is not enabled
  username: "dev"
  password: "dev"
  # add custom params to mongodump (eg. Auth or SSL support), leave blank if not needed
  params: "--authenticationDatabase dev"
# SFTP upload (optional)
sftp:
  host: "SFTP-IP"
  port: 21
  username: "sftp"
  password: "sftp"
  # dir must exist on the SFTP server
  dir: "backup"
# Slack notifications (optional)
#slack:
#  url: https://hooks.slack.com/services/xxxx/xxx/xx
#  channel: devops-alerts
#  username: mgob
  # 'true' to notify only on failures
#  warnOnly: false)

```

Any idea on this ?

Thank you
