### ISSUE TITLE
Chart: invalid default in configMap which must be deleted in values override

### ISSUE THREAD

**Issue by PierreBeucher** [stefanprodan/mgob#86]
Currently the [`chart/values.yaml`](https://github.com/stefanprodan/mgob/blob/775154c441a82ded839ebbe5cc3a3d322d4b0e60/chart/values.yaml#L40) specifies a few examples configuration such as:

```
configMap:
  name: "mgob-config"
  data:
    # Add each plan as per below.
    the-first-database.yml: |
    [...]
    the-second-database.yml: |
    [...]
```

When deploying the chart with a custom `values.yaml` config such as:

```
configMap:
  name: "mgob-config"
  data:
    my-app.yml: |
      target:
        host: "my-mongodb"
        [...]
```

The resulting `ConfigMap` contains the default example config (which obviously won't work) alongside desired config - it requires to specifically nullify the examples configs before deploying with the chart, for example:

```
configMap:
  name: "mgob-config"
  data:
    the-first-database.yml: null
    the-second-database.yml: null
    my-app.yml: |
    [...]
```

It would be better if possible to have the default configMap value empty by default with the same examples commented out, something like:

```
configMap:
  name: "mgob-config"
  data: {}
    # Add each plan as you wish, for example:
    # the-first-database.yml: |
    # [...]
    # the-second-database.yml: |
    # [...]
```
