### ISSUE TITLE
mongodump error: unexpected word

### ISSUE THREAD

**Issue by BenSchZA** [stefanprodan/mgob#93]
Getting the following error from mongodump. It's quite cryptic. I'm using a slight variation of the Kubernetes example configuration, on AWS - making the necessary changes to the persistent volumes for AWS rather than GCP.

```
time="2019-11-14T15:30:00Z" level=info msg="Backup started" plan=REDACTED
time="2019-11-14T15:30:00Z" level=error msg="Backup failed mongodump log /bin/sh: syntax error: unexpected word (expecting ")") : exit status 2" plan=REDACTED
time="2019-11-14T15:30:00Z" level=info msg="Next run at 2019-11-14 15:35:00 +0000 UTC" plan=REDACTED
```

```
---
kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    role: mongo-backup
  name: mgob-config
  namespace: mgob
data:
  molecule-alpha-nightly.yml: |
    target:
      host: "REDACTED.svc.cluster.local"
      port: 27017
      database: "REDACTED"
      username: "REDACTED"
      password: 'REDACTED'
    scheduler:
      cron: "*/5 * * * *"
      retention: 5
      timeout: 60
    s3:
      url: "https://s3.amazonaws.com/"
      bucket: "mgob-backup-REDACTED"
      accessKey: "REDACTED"
      secretKey: "REDACTED"
      api: "S3v4"
    slack:
      url: REDACTED
      channel: mongo_notifications
      username: mgob
      # 'true' to notify only on failures 
      warnOnly: false
```

What I've tried:

1. Change from `mgob:edge` to `mgob:1.0`
2. Change host settings etc.

What I suspect:

1. Might be due to AWS S3 permissions or settings

Any ideas?
